theme: minima
title: Nicole Park
email: nicolepark@berkeley.edu
phone: 925-989-7715
description: Data Scientist

navbar-links:
  Teaching: "teaching"
  Author's home: "https://nicole-park.github.io"

