theme: jekyll-theme-minimal
title: Hi, I'm Nicole Park.
subtitle: Data Science and Economics Undergraduate @ UC Berkeley (2023)
logo: <img src="nicoledraw.png" alt="nicoledraw" width="120" height="120"/>
